version: '3'
services:
  strapi:
    image: dcc-strapi:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - postgres
    volumes:
      - ./app:/srv/app
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
    ports:
      - "1337:1337"


  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'


  caddy:
    image: 'caddy:2-alpine'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - strapi
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
    
volumes:
  caddy-data:
  caddy-config:
  postgres-data:

