version: '3'
services:
  strapi:
    image: dochoichu/strapi:latest
    build:
      context: app
      dockerfile: ../Dockerfile
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - postgres
    volumes:
      - strapi-uploads:/app/public/uploads

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

  caddy:
    image: 'caddy:2-alpine'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - strapi
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
        
volumes:
  caddy-data:
  caddy-config:
  postgres-data:
  strapi-uploads:

